//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSB.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vsb_vehicle
    {
        public vsb_vehicle()
        {
            this.vsb_service_action = new HashSet<vsb_service_action>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public string Description { get; set; }
        public int TypeID { get; set; }
        public bool Deleted { get; set; }
        public byte[] Image { get; set; }
        public System.DateTime ProductionDate { get; set; }
    
        public virtual dictionary_brand dictionary_brand { get; set; }
        public virtual dictionary_model dictionary_model { get; set; }
        public virtual dictionary_vehicle_type dictionary_vehicle_type { get; set; }
        public virtual vsb_car vsb_car { get; set; }
        public virtual ICollection<vsb_service_action> vsb_service_action { get; set; }
    }
}
