//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSB.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vsb_car
    {
        public int ID { get; set; }
        public int EngineTypeID { get; set; }
        public int BodyTypeID { get; set; }
        public int DriveTypeID { get; set; }
        public Nullable<int> EngineVolume { get; set; }
        public string VersionName { get; set; }
        public string RegistrationNumber { get; set; }
        public string CustomName { get; set; }
        public string VIN { get; set; }
        public System.DateTime FirstRegistrationDate { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int WheelsNumber { get; set; }
    
        public virtual dictionary_body_type dictionary_body_type { get; set; }
        public virtual dictionary_drive_type dictionary_drive_type { get; set; }
        public virtual dictionary_enigine_type dictionary_enigine_type { get; set; }
        public virtual vsb_vehicle vsb_vehicle { get; set; }
    }
}
