//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSB.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vsb_service_action
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ActionTypeID { get; set; }
        public int VehicleID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public System.DateTime Date { get; set; }
        public bool Deleted { get; set; }
        public int OwnerID { get; set; }
    
        public virtual dictionary_action_type dictionary_action_type { get; set; }
        public virtual vsb_service vsb_service { get; set; }
        public virtual vsb_vehicle vsb_vehicle { get; set; }
    }
}
