//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSB.Core.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vsbDb : DbContext
    {
        public vsbDb()
            : base("name=vsbDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dictionary_action_type> dictionary_action_type { get; set; }
        public virtual DbSet<dictionary_body_type> dictionary_body_type { get; set; }
        public virtual DbSet<dictionary_brand> dictionary_brand { get; set; }
        public virtual DbSet<dictionary_drive_type> dictionary_drive_type { get; set; }
        public virtual DbSet<dictionary_enigine_type> dictionary_enigine_type { get; set; }
        public virtual DbSet<dictionary_model> dictionary_model { get; set; }
        public virtual DbSet<dictionary_vehicle_type> dictionary_vehicle_type { get; set; }
        public virtual DbSet<vsb_car> vsb_car { get; set; }
        public virtual DbSet<vsb_service> vsb_service { get; set; }
        public virtual DbSet<vsb_service_action> vsb_service_action { get; set; }
        public virtual DbSet<vsb_vehicle> vsb_vehicle { get; set; }
    }
}
